version: '3'
services:

  # Install dependencies
  npm:
    entrypoint: npm
    image: lambci/lambda:build-nodejs8.10
    volumes:
      - ./:/var/task

  # Lock dependencies
  lock:
    command: npm install
    image: lambci/lambda:build-nodejs8.10
    volumes:
      - ./:/var/task

  # Build dependencies
  build:
    command: npm install --production
    image: lambci/lambda:build-nodejs8.10
    volumes:
      - nodejs:/opt/nodejs
      - ./package-lock.json:/opt/nodejs/package-lock.json
      - ./package.json:/opt/nodejs/package.json
    working_dir: /opt/nodejs

  # Package layer
  package:
    command: zip -r /var/task/package.zip .
    image: lambci/lambda:build-nodejs8.10
    volumes:
      - nodejs:/opt/nodejs
      - ./:/var/task
    working_dir: /opt

  # Test
  test:
    command: index.handler '{"path":"/health","httpMethod":"GET"}'
    env_file: .env
    image: lambci/lambda:nodejs8.10
    volumes:
      - ./:/var/task
      - nodejs:/opt/nodejs

volumes:
  nodejs:
