version: '3'
services:

  # Base image
  base: &base
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_DEFAULT_REGION:
      AWS_SECRET:
      AWS_SECRET_ACCESS_KEY:
    image: lambci/lambda:build-nodejs8.10
    network_mode: bridge
    volumes:
      - ./:/var/task
      - ./node_modules:/opt/nodejs/node_modules

  # Build
  build:
    <<: *base

  # Test
  test:
    <<: *base
    command: index.handler '{"path":"/health","httpMethod":"GET"}'
    image: lambci/lambda:nodejs8.10
