version: '3'
services:

  # Install dependencies
  npm:
    entrypoint: npm
    image: lambci/lambda:build-nodejs8.10
    volumes:
      - ./:/var/task

  # Build dependencies
  build:
    command: npm install --production
    image: lambci/lambda:build-nodejs8.10
    volumes:
      - opt_nodejs:/opt/nodejs
      - ./package-lock.json:/opt/nodejs/package-lock.json
      - ./package.json:/opt/nodejs/package.json
    working_dir: /opt/nodejs

  # Test
  test:
    command: index.handler '{"path":"/slash/test","httpMethod":"POST"}'
    env_file: .env
    image: lambci/lambda:nodejs8.10
    volumes:
      - ./:/var/task
      - opt_nodejs:/opt/nodejs

volumes:
  opt_nodejs:
